#!/usr/bin/env bash
rm -rf dist
mkdir -p dist
echo "build src/index.ls -> dist/index.js ..."
./node_modules/.bin/lsc -cp --no-header src/index.ls > dist/index.js
echo "minifying index.js ..."
./node_modules/.bin/uglifyjs dist/index.js -m -c > dist/index.min.js
echo "copy dist files to web ..."
rm -rf web/static/assets/lib/csv4xls/dev
mkdir -p web/static/assets/lib/csv4xls/dev
cp -R dist/* web/static/assets/lib/csv4xls/dev
echo "done."
